name: Check Subscription Expiry
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Expiry
        run: |
          limit_date=$(jq -r '.date' limit_date.json)
          today=$(date +%Y-%m-%d)
          
          if [[ "$today" > "$limit_date" ]]; then
            echo "[]" > J556RDWCVJK
            git config --global user.name "VordrBot"
            git config --global user.email "bot@vordr.com"
            git add J556RDWCVJK
            git commit -m "Abonelik suresi doldu"
            git push
          fi
