name: 26 Gun Sayaci
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  countdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 countdown_timer.py
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🔄 Sayac guncellendi" || true
          git push
