name: Fetch and Clean Free VPN Links
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Collector Engine
        run: |
          python collector.py

      - name: Commit and Push VIP Links
        run: |
          git config --global user.name "VordrBot"
          git config --global user.email "bot@vordr.com"
          
          # Dosyayı takibe al
          git add toplanan_linkler.txt
          
          # Eğer dosyada gerçekten bir değişiklik varsa commit et ve standart pushla
          if ! git diff --cached --quiet; then
            git commit -m "Zirhli Cloudflare VIP Havuzu Yenilendi: $(date +'%H:%M:%S')"
            git push origin HEAD:main
          else
            echo "[-] Degisiklik yok, push atilmiyor."
          fi
