name: Update configs

on:
  workflow_dispatch:

  schedule:
    - cron: "*/55 * * * *"

  push:
    paths:
      - "scripts/**"
      - ".github/workflows/update.yml"
      - "package.json"
      - "names.txt"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Repository'yi indir
        uses: actions/checkout@v4

      - name: Node.js kur
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: npm paketlerini kur
        run: npm install

      - name: Rust kur
        uses: dtolnay/rust-toolchain@stable

      - name: hpwnr kur
        run: |
          cargo install --git https://github.com/Omegaplexx/hpwnr.git --locked

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Python scriptini çalıştır
        run: |
          python scripts/update.py

      - name: Değişiklikleri GitHub'a kaydet
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Toplanan_linkler.txt

          if git diff --cached --quiet; then
            echo "Yeni değişiklik yok."
          else
            git commit -m "Update configs"
            git push
          fi
