name: Sub Dosyalarini Guncelle

on:
  push:
    paths:
      - 'KODLARY'
      - 'CONFIG'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: python update.py
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.node.red.github.com"
          git pull origin main --rebase || true
          git add .
          git commit -m "${COMMIT_MSG:-Guncellendi [skip ci]}" || echo "Degisiklik yok"
          git push
